config/routes.rb
Rails.application.routes.draw do
  root 'calclient#index'
  get 'calclient/call'
  post 'calclient/call', as: '/call'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calclient_controller.rb
class CalclientController < ApplicationController
  # Developer note: To extect functionality to another "server", add the server name to the `valid_servers` array, and include the required server + parameters in the `if..then` statement at the bottom of the `call` action. Don't forget to update tests!

  # Live version of this app can be found at: https://radiant-fjord-19093.herokuapp.com/

  # Developer notes for Goal 2:
    # I had named my two value parameters "num1" and "num2". Goal 2 requires that I rename them to fit more types of variables so I went with 'value1' and 'value2'.
    # My logic was based on always having two integers, so it had to be reworked slightly. This actually reduced the code footprint, so it was a good thing.

  def index
    @information = { message: "Hello World!" }
  end

  def call
    valid_servers = ["sum", "subtract", "concanate_upcase"]

    # Refute any nil, blank or empty 'server'.
    return @information = { message: "Invalid server name." } if params[:server].nil? || params[:server].empty? || params[:server].blank?
    # Convert the provided 'server' to lowercase.
    params['server'] = params['server'].downcase

    # Identify the server to communicate with & return information to the client.
    if params[:server] == 'sum'
      return @information = { message: "Value1 must be an integer." } if !value_is_integer(params[:value1])
      return @information = { message: "Value2 must be an integer." } if !value_is_integer(params[:value2])
      return @information = { message: "Server name: '#{params[:server]}'.", value: (params[:value1].to_i + params[:value2].to_i) }
    elsif params[:server] == 'subtract'
      return @information = { message: "Value1 must be an integer." } if !value_is_integer(params[:value1])
      return @information = { message: "Value2 must be an integer." } if !value_is_integer(params[:value2])
      return @information = { message: "Server name: '#{params[:server]}'.", value: (params[:value1].to_i - params[:value2].to_i) }
    elsif params[:server] == 'concanate_upcase'
      return @information = { message: "Value1 must be a string." } if !value_is_string(params[:value1])
      return @information = { message: "Value2 must be a string." } if !value_is_string(params[:value2])
      return @information = { message: "Server name: '#{params[:server]}'.", value: (params[:value1].upcase + params[:value2].upcase) }
    else
      return @information = { message: "Invalid server name." }
    end

  end

  private
    def value_is_integer(value)
      valid_integers = /\A[-+]?[0-9]*\.?[0-9]+\Z/
      if !valid_integers.match(value) 
        return false
      else
        return true
      end
    end

    def value_is_string(value)
      valid_strings = /^[A-Za-z]+$/
      if !valid_strings.match(value)
        return false
      else
        return true
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calclient_helper.rb
module CalclientHelper
end

app/views/calclient/_buttons.html.erb
<div class="button_container">
  <%= button_to "Sum", call_path, params: { server: "sum", value1: 2, value2: 8 } %>
  <%= button_to "Subtract", call_path, params: { server: "subtract", value1: 5, value2: 4 }, form_class: "button_to" %>
  <%= button_to "Concanate", call_path, params: { server: "concanate_upcase", value1: "example", value2: "text" }, form_class: "button_to" %>
  <%= button_to "Invalid", call_path, params: { server: "   ", value1: '1', value2: 8 }, form_class: "button_to" %>
</div>

app/views/calclient/_display.html.erb
<% if @information %>
  <h1 class="header">AffiniPay CalClient API</h1>
  <div class="info_container">
    <h3 class="message"><%= @information[:message] %></h3>
    <% if @information %>
      <p class="value"><%= @information[:value] %></p>
    <% end %>
  </div>
<% end %>

app/views/calclient/_form.html.erb
<h1 class="title">Custom Parameters</h1>
<%= form_with(url: call_path, local: true, html: {class: "form_container"}) do |f| %>

<%= f.label :server %>
<%= f.text_field :server %>

<%= f.label :value1 %>
<%= f.text_field :value1 %>

<%= f.label :value2 %>
<%= f.text_field :value2 %>

<%= f.submit "Submit" %>
<% end %>

app/views/calclient/call.html.erb
<%= render 'display' %>
<%= render 'buttons' %>
<%= render 'form' %>

app/views/calclient/index.html.erb
<%= render 'display' %>
<%= render 'buttons' %>
<%= render 'form' %>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'%>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>AffiniPay Assessment</title>
  <meta charset="utf-8">
  <%= render 'layouts/rails_default' %>
  <%= render 'layouts/shim' %>
</head>

<body>
  <div>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>

</html>